### ISSUE TITLE
Overwrites existing .bash_profile :O

### ISSUE THREAD

**Issue by kristianmandrup** [mathiasbynens/dotfiles#501]
Tried running the git-free install. I was surprised to learn that my .bash_profile was overwritten.
Any way I can revert or find my original .bash_profile?
This is a huge concern for me...

**Comment by mathiasbynens** [comment]
> Any way I can revert or find my original `.bash_profile`?

Nope, sorry. What did you think “installing” the dotfiles would do? Should I clarify this in the readme?

**Comment by abdulwahid24** [comment]
@mathiasbynens I would suggest instead of overwriting the existing `.bash_profile` you can create with different name such as `.dotfile_profile` and then you can import this at the end of file in existing `.bash_profile`. 

I lost all my important settings. :(

**Comment by mathiasbynens** [comment]
There is a warning when you run `bootstrap.sh`: https://github.com/mathiasbynens/dotfiles/blob/e7ef66da4f6a077261286df3729d823a1d39e04b/bootstrap.sh#L16

**Comment by nvartolomei** [comment]
@mathiasbynens pst! https://github.com/nvartolomei/dotfiles/blob/master/script/bootstrap `do_backup`

**Comment by Izhaki** [comment]
Seriously???

I've just lost my ./bash_profile!!!

> This may overwrite existing files in your home directory.

Well... it _may_ doesn't quite cut it doesn't quite say which files! Something like this probably make you thing twice:

> This will overwrite your .bash_profile file.

And why do you override anyhow? When you install `nvm` it just adds to that very file - doesn't override it.

I'd seriously consider not doing what you are doing at the moment. It's pretty insane.

**Comment by ealeksandrov** [comment]
@Izhaki 
This is `Mathias’s dotfiles`. Not `dotfiles enhancer for everyone`.

Also there is huge warning at the top of readme:
> Warning: If you want to give these dotfiles a try, you should first fork this repository, review the code, and remove things you don’t want or need. Don’t blindly use my settings unless you know what that entails. Use at your own risk!

Why should it append `.bash_profile`? This is a backup of all settings for one particular person. This means that person have ability to quickly restore all settings in one command. Appending `.bash_profile` only make sense for some general public tools that need it to work.
This is not "awesome macOS booster", this is "Mathias’s private settings"! It shouldn't be used straight from his repository without any alternations!

**Comment by Izhaki** [comment]
@ealeksandrov 

I completely understand what you are saying.

But there is some disregard to how people actually behave:

- You search how to add your git branch to the prompt.
- You find a link to this repo on SO.
- It looks awesome, under active development, and has gazillion of starts (making it trustworthy).
- You decide to try it out.

When was the last time you, or anyone you know, have read T&C?

One pivotal concept in HCI is that users are either in:

- task completion mode
- exploration mode

Whilst in the former, people take any shortcut possible in order to complete the task.

So accidents like this are destined to repeat.

I don't think the solution is important here (@nvartolomei one would save me). It is the **denial of the problem** that is the real issue.

**Comment by ealeksandrov** [comment]
I don't think that Mathias **should** do something just because his project is so popular and many people don't read readme (that's not T&C, that's top of Readme).

This is not an issue for source value of project, so it's ultimately for author to decide how to handle it. It's just a dump of shared code, it's not a product with support.

Even License states it clearly - NO Liability or Warranty.

**Comment by mathiasbynens** [comment]
As stated [before](https://github.com/mathiasbynens/dotfiles/issues/501#issuecomment-172882809), even if you choose to ignore the README, you are presented with a warning when running `bootstrap.sh`: https://github.com/mathiasbynens/dotfiles/blob/e7ef66da4f6a077261286df3729d823a1d39e04b/bootstrap.sh#L16

I’m locking this issue as I believe everything has already been said.
