### ISSUE TITLE
.osx: Minor HOME vs {HOME}

### ISSUE THREAD

**Issue by s10wen** [mathiasbynens/dotfiles#568]
Wondering if `HOME` here: https://github.com/mathiasbynens/dotfiles/blob/3a47ebe1faf72222b1915853a3ce093ac8908853/.osx#L582

should be `{HOME}` like the other references, e.g. 
https://github.com/mathiasbynens/dotfiles/blob/3a47ebe1faf72222b1915853a3ce093ac8908853/.osx#L212

**Comment by kevinvdburgt** [comment]
Yup, $HOME is indeed /Users/<username>/

**Comment by Tatsh** [comment]
It is generally not necessary.

`${HOME}` === `$HOME` in Bash. The script could use `${HOME}` but it will not make a difference because there is no need to worry about collisions with a string because the last part is a `/` which cannot  be part of a Bash variable.

```bash
# bad:
a="$HOMEaaaa"

# good:
a="${HOME}aaaa"

# not great but still works because / and other characters are not valid for a variable
a="$HOME/aaa"
```

The only thing I would say that line is missing is full quotes (escaping) around the path that is created via the concatenation. But this is again not totally necessary if there are no spaces in the outputted path. Otherwise every space must be escaped as `\ ` in particular for the variable `themeName` on that line.

**Comment by s10wen** [comment]
Hey @Tatsh thanks for the thorough answer there :+1:
